learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views


# tempalte tagging 
app_name = 'basic_app'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context=context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')


def base(request):
    return render(request, 'basic_app/base.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Brand</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>

</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block%}

<h1>Welcome to HomePage</h1>
<h2>example template inheritance</h2>
<h1>{{ text|cut:'hello' }}</h1>
<h1>{{ number|add:"99" }}</h1>

{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block%}

<h1>Welcome to Other</h1>
<h2>example template inheritance</h2>

{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Relative Url Templates</title>
</head>

<body>
    <h1>Welcome to Relative Url Templates</h1>
    <a href="{% url 'basic_app:other' %}">the other page</a>
    <a href="{% url 'admin:index' %}">Admin page</a>
    <a href="{% url 'index' %}">Link to index</a>
</body>

</html>